# Generated by Django 5.2.4 on 2025-09-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_status", "0002_initial"),
        ("histories_configurations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="payment_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="histories_configurations.paymenttype",
                verbose_name="Tipo de pago",
            ),
        ),
    ]
