# Generated by Django 5.2.4 on 2025-09-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("histories_configurations", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentstatus",
            options={
                "verbose_name": "Estado de pago",
                "verbose_name_plural": "Estados de pago",
            },
        ),
    ]
