# Generated by Django 5.2.4 on 2025-09-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("histories_configurations", "0003_alter_paymentstatus_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentstatus",
            options={
                "ordering": ["name"],
                "verbose_name": "Estado de pago",
                "verbose_name_plural": "Estados de pago",
            },
        ),
    ]
