# Generated by Django 5.2.4 on 2025-09-26 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("histories_configurations", "0004_alter_paymentstatus_options"),
        ("patients_diagnoses", "0002_alter_medicalrecord_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="history",
            options={
                "ordering": ["-history_date", "-created_at"],
                "verbose_name": "Historial",
                "verbose_name_plural": "Historiales",
            },
        ),
        migrations.AddField(
            model_name="history",
            name="history_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha del historial"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="history",
            unique_together={("patient", "history_date")},
        ),
    ]
