# Generated by Django 5.2.4 on 2025-09-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "histories_configurations",
            "0005_alter_history_options_history_history_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="history_date",
            field=models.DateField(verbose_name="Fecha del historial"),
        ),
    ]
