# Generated by Django 5.2.4 on 2025-10-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("histories_configurations", "0006_alter_history_history_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContraceptiveMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Metodo Anticonceptivo",
                "verbose_name_plural": "Metodos Anticonceptivos",
                "db_table": "contraceptive_method",
                "ordering": ["name"],
            },
        ),
    ]
