# Generated by Django 5.2.4 on 2025-10-06 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("histories_configurations", "0007_contraceptivemethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="contraceptive_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="histories_configurations.contraceptivemethod",
                verbose_name="Método anticonceptivo",
            ),
        ),
    ]
