# Generated by Django 5.2.4 on 2025-10-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("histories_configurations", "0008_history_contraceptive_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="actual_weight",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Peso actual"
            ),
        ),
    ]
