# Generated by Django 5.2.4 on 2025-10-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("histories_configurations", "0009_history_actual_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="DIUType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de dispositivo intrauterino",
                "verbose_name_plural": "Tipos de dispositivos intrauterinos",
                "db_table": "diu_types",
                "ordering": ["name"],
            },
        ),
    ]
