# Generated by Django 5.2.4 on 2025-09-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
