# Generated by Django 5.2.4 on 2025-09-28 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_profiles", "0003_auto_20250927_1145"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userverificationcode",
            options={
                "managed": True,
                "ordering": ["-created_at"],
                "verbose_name": "Código de verificación de usuario",
                "verbose_name_plural": "Códigos de verificación de usuarios",
            },
        ),
    ]
