# Generated by Django 5.2.4 on 2025-10-06 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_profiles", "0004_alter_userverificationcode_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userverificationcode",
            name="is_used",
            field=models.BooleanField(default=False, verbose_name="¿Usado?"),
        ),
        migrations.AddField(
            model_name="userverificationcode",
            name="target_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email objetivo"
            ),
        ),
        migrations.AddField(
            model_name="userverificationcode",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_codes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="userverificationcode",
            name="verification_type",
            field=models.CharField(
                choices=[
                    ("email_verification", "Verificación de email"),
                    ("email_change", "Cambio de email"),
                    ("password_change", "Cambio de contraseña"),
                ],
                default="email_verification",
                max_length=50,
                verbose_name="Tipo de verificación",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userverificationcode",
            unique_together={("user", "verification_type")},
        ),
    ]
