# Generated by Django 5.2.4 on 2025-10-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_profiles", "0005_userverificationcode_is_used_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userverificationcode",
            unique_together=set(),
        ),
    ]
