# Generated by Django 5.2.4 on 2025-09-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients_diagnoses", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="medicalrecord",
            unique_together={("patient", "diagnose", "diagnosis_date")},
        ),
    ]
